#!/bin/bash

if [ -e ~/.bashrc ] ; then
	. ~/.bashrc
fi
PLAN9=${PLAN9:-/Users/masato/Documents/Pocket7878/plan9port}

bin=$PLAN9/bin
IFS=$'\n'

for file in $($bin/macargv)
do
	$bin/macedit "$file"
done
